package com.applovin.impl.sdk.c;

import com.applovin.impl.sdk.utils.AppLovinSdkExtraParameterKey;
import com.applovin.impl.sdk.utils.u;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;

public class a<T> extends b<T> {
    public static final b<Long> aJA = d("ahdm", 500L);
    public static final b<Long> aJB = d("ad_view_refresh_precache_request_viewability_undesired_flags", 246L);
    public static final b<Boolean> aJC = d("ad_view_refresh_precache_request_enabled", true);
    public static final b<Boolean> aJD = d("ssvaal", false);
    public static final b<Boolean> aJE = d("fabsina", false);
    public static final b<Boolean> aJF = d("fabsiaif", false);
    public static final b<Long> aJG = d("famttl_ms", 0L);
    public static final b<Long> aJH = d("ad_expiration_ms", Long.valueOf(TimeUnit.HOURS.toMillis(4)));
    public static final b<Long> aJI = d("native_ad_expiration_ms", Long.valueOf(TimeUnit.HOURS.toMillis(4)));
    public static final b<Boolean> aJJ = d("rena", true);
    public static final b<Boolean> aJK = d("native_downscale_icon_fix", false);
    public static final b<Long> aJL = d("fullscreen_ad_displayed_timeout_ms", -1L);
    public static final b<Long> aJM = d("freast_ms", -1L);
    public static final b<Long> aJN = d("ad_hidden_timeout_ms", -1L);
    public static final b<Boolean> aJO = d("schedule_ad_hidden_on_ad_dismiss", false);
    public static final b<Boolean> aJP = d("schedule_ad_hidden_on_single_task_app_relaunch", false);
    public static final b<Long> aJQ = d("ad_hidden_on_ad_dismiss_callback_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1)));
    public static final b<Boolean> aJR = d("proe", false);
    public static final b<Integer> aJS = d("mute_state", 2);
    public static final b<String> aJT = d("saf", "");
    public static final b<String> aJU = d("saui", "");
    public static final b<Integer> aJV = d("mra", -1);
    public static final b<String> aJW = d("mra_af", "INTER,REWARDED,REWARDED_INTER,BANNER,LEADER,MREC");
    public static final b<Boolean> aJX = d("fadiafase", true);
    public static final b<Boolean> aJY = d("fadwvcv", true);
    public static final b<Boolean> aJZ = d("bfarud", false);
    public static final b<String> aJe = d("afi", "");
    public static final b<Long> aJf = d("afi_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5)));
    public static final b<String> aJg = d("mediation_endpoint", "https://ms.applovin.com/");
    public static final b<String> aJh = d("mediation_backup_endpoint", "https://ms.applvn.com/");
    public static final b<Long> aJi = d("fetch_next_ad_retry_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(2)));
    public static final b<Long> aJj = d("fetch_next_ad_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<Long> aJk = d("fetch_mediation_debugger_info_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(7)));
    public static final b<Boolean> aJl = d("auto_init_mediation_debugger", true);
    public static final b<String> aJm = d("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
    public static final b<Long> aJn = d("max_signal_provider_latency_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<Long> aJo = d("default_adapter_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10)));
    public static final b<Long> aJp = d("ad_refresh_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<Long> aJq = d("ad_load_failure_refresh_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<String> aJr = d("ad_load_failure_refresh_ignore_error_codes", "204");
    public static final b<Long> aJs = d("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
    public static final b<Boolean> aJt = d("refresh_ad_view_timer_responds_to_background", true);
    public static final b<Boolean> aJu = d("refresh_ad_view_timer_responds_to_store_kit", true);
    public static final b<Boolean> aJv = d("refresh_ad_view_timer_responds_to_window_visibility_changed", false);
    public static final b<Boolean> aJw = d("avrsponse", false);
    public static final b<Boolean> aJx = d(AppLovinSdkExtraParameterKey.ALLOW_IMMEDIATE_AUTO_REFRESH_PAUSE, false);
    public static final b<Long> aJy = d("fullscreen_display_delay_ms", 0L);
    public static final b<Boolean> aJz = d("susaode", false);
    public static final b<Boolean> aKa = d("inacc", Boolean.valueOf(u.N((List<String>) Arrays.asList(new String[]{"com.textmeinc.textme", "com.textmeinc.freetone", "com.textmeinc.textme3", "com.jaumo", "com.jaumo.casual", "com.pinkapp", "com.jaumo.mature", "com.jaumo.prime", "com.jaumo.gay", "com.jaumo.lesbian"}))));
    public static final b<String> aKb = d("pbataipaf", "");
    public static final b<Long> aKc = d("bwt_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<Long> aKd = d("twt_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30)));
    public static final b<Long> aKe = d("adiets_sec", Long.valueOf(TimeUnit.MINUTES.toSeconds(1)));
    public static final b<Boolean> aKf = d("fetch_mediated_ad_gzip", true);
    public static final b<Boolean> aKg = d("max_postback_gzip", true);
}
