package com.applovin.impl.sdk.c;

import android.net.Uri;
import com.applovin.impl.adview.AppLovinTouchToClickListener;
import com.applovin.impl.b.n;
import com.applovin.impl.sdk.utils.AppLovinSdkExtraParameterKey;
import com.applovin.impl.sdk.utils.p;
import com.applovin.mediation.MaxAdFormat;
import com.applovin.sdk.AppLovinAdSize;
import com.ironsource.mediationsdk.utils.IronSourceConstants;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class b<T> implements Comparable {
    public static final b<Boolean> aKA = d("exception_handler_enabled", true);
    public static final b<Integer> aKB = d("network_thread_count", 2);
    public static final b<Integer> aKC = d("aei", -1);
    public static final b<Integer> aKD = d("mei", -1);
    public static final b<Boolean> aKE = d("bdae", false);
    public static final b<Boolean> aKF = d("tewllm", true);
    public static final b<Boolean> aKG = d("lisvib", false);
    public static final b<Boolean> aKH = d("tewplosda", true);
    public static final b<Boolean> aKI = d("srwbe", false);
    public static final b<Integer> aKJ = d("malaera", -1);
    public static final b<String> aKK = d("eralaf", "");
    public static final b<Boolean> aKL = d("eraziie", false);
    public static final b<String> aKM = d("ps_atu", "");
    public static final b<Boolean> aKN = d("ah_cvc", true);
    public static final b<Boolean> aKO = d("ah_cdde", true);
    public static final b<Boolean> aKP = d("ah_crut", true);
    public static final b<Boolean> aKQ = d("init_omsdk", true);
    public static final b<String> aKR = d("omsdk_partner_name", "applovin");
    public static final b<Boolean> aKS = d("publisher_can_show_consent_dialog", true);
    public static final b<String> aKT = d("consent_dialog_url", "https://assets.applovin.com/gdpr/flow_v1/gdpr-flow-1.html");
    public static final b<Boolean> aKU = d("consent_dialog_immersive_mode_on", false);
    public static final b<Long> aKV = d("consent_dialog_show_from_alert_delay_ms", 450L);
    public static final b<Boolean> aKW = d("alert_consent_for_dialog_rejected", false);
    public static final b<Boolean> aKX = d("alert_consent_for_dialog_closed", false);
    public static final b<Boolean> aKY = d("alert_consent_for_dialog_closed_with_back_button", false);
    public static final b<Boolean> aKZ = d("alert_consent_after_init", false);
    private static final List<?> aKh = Arrays.asList(new Class[]{Boolean.class, Float.class, Integer.class, Long.class, String.class});
    private static final Map<String, b<?>> aKi = new HashMap(512);
    public static final b<Boolean> aKk = d("is_disabled", false);
    public static final b<String> aKl = d("device_id", "");
    public static final b<Boolean> aKm = d("rss", true);
    public static final b<Boolean> aKn = d("rssoitf", false);
    public static final b<String> aKo = d("device_token", "");
    public static final b<Long> aKp = d("publisher_id", 0L);
    public static final b<Boolean> aKq = d("is_verbose_logging", false);
    public static final b<String> aKr = d("sc", "");
    public static final b<String> aKs = d("sc2", "");
    public static final b<String> aKt = d("sc3", "");
    public static final b<String> aKu = d("server_installed_at", "");
    public static final b<Boolean> aKv = d("pnrc", false);
    public static final b<Boolean> aKw = d("clear_completion_callback_on_failure", false);
    public static final b<Long> aKx = d("sicd_ms", 0L);
    public static final b<Integer> aKy = d("logcat_max_line_size", 1000);
    public static final b<Integer> aKz = d("stps", 2);
    public static final b<String> aLA = d("token_type_prefixes_r", "4!");
    public static final b<String> aLB = d("token_type_prefixes_arj", "json_v3!");
    public static final b<String> aLC = d("top_level_events", "landing,paused,resumed,cf_start,tos_ok,gdpr_ok,ref,rdf,checkout,iap");
    public static final b<String> aLD = d("valid_super_property_types", String.class.getName() + "," + Integer.class.getName() + "," + Long.class.getName() + "," + Double.class.getName() + "," + Float.class.getName() + "," + Date.class.getName() + "," + Uri.class.getName() + "," + List.class.getName() + "," + Map.class.getName());
    public static final b<Boolean> aLE = d("persist_super_properties", true);
    public static final b<Integer> aLF = d("super_property_string_max_length", 1024);
    public static final b<Integer> aLG = d("super_property_url_max_length", 1024);
    public static final b<Boolean> aLH = d("use_per_format_cache_queues", true);
    public static final b<Boolean> aLI = d("cache_cleanup_enabled", false);
    public static final b<Long> aLJ = d("cache_file_ttl_seconds", Long.valueOf(TimeUnit.DAYS.toSeconds(1)));
    public static final b<Integer> aLK = d("cache_max_size_mb", -1);
    public static final b<String> aLL = d("precache_delimiters", ")]', ");
    public static final b<Boolean> aLM = d("ad_resource_caching_enabled", true);
    public static final b<String> aLN = d("resource_cache_prefix", "https://vid.applovin.com/,https://stage-vid.applovin.com/,https://pdn.applovin.com/,https://stage-pdn.applovin.com/,https://img.applovin.com/,https://stage-img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://stage-assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://stage-vid.applovin.com/,http://pdn.applovin.com/,http://stage-pdn.applovin.com/,http://img.applovin.com/,http://stage-img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://stage-assets.applovin.com/,http://cdnjs.cloudflare.com/,http://u.appl.vn/,https://u.appl.vn/,https://res.applovin.com/,https://res1.applovin.com/,https://res2.applovin.com/,https://res3.applovin.com/,http://res.applovin.com/,http://res1.applovin.com/,http://res2.applovin.com/,http://res3.applovin.com/");
    public static final b<String> aLO = d("preserved_cached_assets", "sound_off.png,sound_on.png,closeOptOut.png,1381250003_28x28.png,zepto-1.1.3.min.js,jquery-2.1.1.min.js,jquery-1.9.1.min.js,jquery.knob.js");
    public static final b<Integer> aLP = d("resource_max_filename_length", 255);
    public static final b<Boolean> aLQ = d("ccrc", false);
    public static final b<Integer> aLR = d("mcct", 3);
    public static final b<Integer> aLS = d("mchct", 3);
    public static final b<Boolean> aLT = d("dficf", false);
    public static final b<Boolean> aLU = d("decr", false);
    public static final b<Boolean> aLV = d("dcrome", false);
    public static final b<Boolean> aLW = d("dcrobs", false);
    public static final b<Boolean> aLX = d("upcan", false);
    public static final b<Boolean> aLY = d("ugfnfhr", false);
    public static final b<Boolean> aLZ = d("lfeufc", false);
    public static final b<Long> aLa = d("alert_consent_after_init_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5)));
    public static final b<Long> aLb = d("alert_consent_after_dialog_rejection_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(30)));
    public static final b<Long> aLc = d("alert_consent_after_dialog_close_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5)));
    public static final b<Long> aLd = d("alert_consent_after_dialog_close_with_back_button_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5)));
    public static final b<Long> aLe = d("alert_consent_after_cancel_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(10)));
    public static final b<Long> aLf = d("alert_consent_reschedule_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5)));
    public static final b<String> aLg = d("text_alert_consent_title", "Make this App Better and Stay Free!");
    public static final b<String> aLh = d("text_alert_consent_body", "If you don't give us consent to use your data, you will be making our ability to support this app harder, which may negatively affect the user experience.");
    public static final b<String> aLi = d("text_alert_consent_yes_option", "I Agree");
    public static final b<String> aLj = d("text_alert_consent_no_option", "Cancel");
    public static final b<Long> aLk = d("ttc_max_click_duration_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1)));
    public static final b<Integer> aLl = d("ttc_max_click_distance_dp", 10);
    public static final b<Integer> aLm = d("ttc_acrsv2a", Integer.valueOf(AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN.ordinal()));
    public static final b<Integer> aLn = d("ttc_acrsnv", Integer.valueOf(AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN.ordinal()));
    public static final b<Integer> aLo = d("ttc_acrsa", Integer.valueOf(AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN.ordinal()));
    public static final b<Integer> aLp = d("ttc_acrsn", Integer.valueOf(AppLovinTouchToClickListener.ClickRecognitionState.ACTION_DOWN.ordinal()));
    public static final b<Integer> aLq = d("ttc_edge_buffer_dp", 0);
    public static final b<String> aLr = d("whitelisted_postback_endpoints", "https://prod-a.applovin.com,https://rt.applovin.com/4.0/pix, https://rt.applvn.com/4.0/pix,https://ms.applovin.com/,https://ms.applvn.com/");
    public static final b<String> aLs = d("fetch_settings_endpoint", "https://ms.applovin.com/");
    public static final b<String> aLt = d("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
    public static final b<String> aLu = d("adserver_endpoint", "https://a.applovin.com/");
    public static final b<String> aLv = d("adserver_backup_endpoint", "https://a.applvn.com/");
    public static final b<String> aLw = d("api_endpoint", "https://d.applovin.com/");
    public static final b<String> aLx = d("api_backup_endpoint", "https://d.applvn.com/");
    public static final b<String> aLy = d("event_tracking_endpoint_v2", "https://rt.applovin.com/");
    public static final b<String> aLz = d("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
    public static final b<Integer> aMA = d("viewability_adview_native_min_height", 0);
    public static final b<Float> aMB = d("viewability_adview_min_alpha", Float.valueOf(10.0f));
    public static final b<Long> aMC = d("viewability_timer_min_visible_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1)));
    public static final b<Long> aMD = d("viewability_timer_interval_ms", 100L);
    public static final b<Integer> aME = d("expandable_close_button_size", 27);
    public static final b<Integer> aMF = d("expandable_h_close_button_margin", 10);
    public static final b<Integer> aMG = d("expandable_t_close_button_margin", 10);
    public static final b<Boolean> aMH = d("expandable_lhs_close_button", false);
    public static final b<Integer> aMI = d("expandable_close_button_touch_area", 0);
    public static final b<Boolean> aMJ = d("iaad", false);
    public static final b<String> aMK = d("js_tag_schemes", "applovin,mopub");
    public static final b<String> aML = d("js_tag_load_success_hosts", "load,load_succeeded");
    public static final b<String> aMM = d("js_tag_load_failure_hosts", "failLoad,load_failed");
    public static final b<Integer> aMN = d("auxiliary_operations_threads", 1);
    public static final b<Long> aMO = d("fullscreen_ad_pending_display_state_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10)));
    public static final b<Long> aMP = d("fullscreen_ad_showing_state_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(2)));
    public static final b<Boolean> aMQ = d("lhs_close_button_video", false);
    public static final b<Integer> aMR = d("close_button_right_margin_video", 4);
    public static final b<Integer> aMS = d("close_button_size_video", 30);
    public static final b<Integer> aMT = d("close_button_top_margin_video", 8);
    public static final b<Integer> aMU = d("video_countdown_clock_margin", 10);
    public static final b<Integer> aMV = d("video_countdown_clock_gravity", 83);
    public static final b<Integer> aMW = d("countdown_clock_size", 32);
    public static final b<Integer> aMX = d("countdown_clock_stroke_size", 4);
    public static final b<Integer> aMY = d("countdown_clock_text_size", 28);
    public static final b<Boolean> aMZ = d("draw_countdown_clock", true);
    public static final b<Boolean> aMa = d("pcro", false);
    public static final b<Boolean> aMb = d("efecobt", false);
    public static final b<Boolean> aMc = d("saewib", false);
    public static final b<Long> aMd = d("fsae_ms", -1L);
    public static final b<Boolean> aMe = d("raae", false);
    public static final b<Integer> aMf = d("vr_retry_count_v1", 1);
    public static final b<Integer> aMg = d("cr_retry_count_v1", 1);
    public static final b<String> aMh = d("text_incent_warning_title", "Attention!");
    public static final b<String> aMi = d("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
    public static final b<String> aMj = d("text_incent_warning_close_option", "Close");
    public static final b<String> aMk = d("text_incent_warning_continue_option", "Keep Watching");
    public static final b<String> aMl = d("text_incent_nonvideo_warning_title", "Attention!");
    public static final b<String> aMm = d("text_incent_nonvideo_warning_body", "You won’t get your reward if the game hasn’t finished.");
    public static final b<String> aMn = d("text_incent_nonvideo_warning_close_option", "Close");
    public static final b<String> aMo = d("text_incent_nonvideo_warning_continue_option", "Keep Playing");
    public static final b<Integer> aMp = d("close_button_touch_area", 0);
    public static final b<Integer> aMq = d("close_button_outside_touch_area", 0);
    public static final b<Boolean> aMr = d("creative_debugger_enabled", true);
    public static final b<Long> aMs = d("viewability_adview_imp_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1)));
    public static final b<Integer> aMt = d("viewability_adview_banner_min_width", 320);
    public static final b<Integer> aMu = d("viewability_adview_banner_min_height", Integer.valueOf(AppLovinAdSize.BANNER.getHeight()));
    public static final b<Integer> aMv = d("viewability_adview_mrec_min_width", Integer.valueOf(MaxAdFormat.MREC.getSize().getWidth()));
    public static final b<Integer> aMw = d("viewability_adview_mrec_min_height", Integer.valueOf(MaxAdFormat.MREC.getSize().getHeight()));
    public static final b<Integer> aMx = d("viewability_adview_leader_min_width", 728);
    public static final b<Integer> aMy = d("viewability_adview_leader_min_height", Integer.valueOf(AppLovinAdSize.LEADER.getHeight()));
    public static final b<Integer> aMz = d("viewability_adview_native_min_width", 0);
    public static final b<Boolean> aNA = d("fahosu", false);
    public static final b<Boolean> aNB = d("nsuttcl", false);
    public static final b<Integer> aNC = d("submit_postback_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(10)));
    public static final b<Integer> aND = d("submit_postback_retries", 4);
    public static final b<Integer> aNE = d("max_postback_attempts", 3);
    public static final b<Integer> aNF = d("max_persisted_postbacks", 100);
    public static final b<Integer> aNG = d("submit_web_tracker_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(7)));
    public static final b<Boolean> aNH = d("sossp", false);
    public static final b<Boolean> aNI = d("spp", true);
    public static final b<Boolean> aNJ = d("retry_on_all_errors", false);
    public static final b<Integer> aNK = d("get_retry_delay_v1", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(10)));
    public static final b<Integer> aNL = d("http_connection_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(30)));
    public static final b<Integer> aNM = d("http_socket_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(20)));
    public static final b<Boolean> aNN = d("force_ssl", false);
    public static final b<Integer> aNO = d("fetch_ad_connection_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(30)));
    public static final b<Integer> aNP = d("fetch_ad_retry_count_v1", 1);
    public static final b<Boolean> aNQ = d("faer", false);
    public static final b<Boolean> aNR = d("faroae", false);
    public static final b<Integer> aNS = d("submit_data_retry_count_v1", 1);
    public static final b<Integer> aNT = d("response_buffer_size", 16000);
    public static final b<Integer> aNU = d("fetch_basic_settings_connection_timeout_ms", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(10)));
    public static final b<Integer> aNV = d("fetch_basic_settings_retry_count", 3);
    public static final b<Boolean> aNW = d("fetch_basic_settings_on_reconnect", false);
    public static final b<Boolean> aNX = d("skip_fetch_basic_settings_if_not_connected", false);
    public static final b<Integer> aNY = d("fetch_basic_settings_retry_delay_ms", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(2)));
    public static final b<Boolean> aNZ = d("idflrwbe", false);
    public static final b<Long> aNa = d("inter_display_delay", 200L);
    public static final b<Long> aNb = d("maximum_close_button_delay_seconds", 999L);
    public static final b<Boolean> aNc = d("respect_close_button", true);
    public static final b<Boolean> aNd = d("lhs_skip_button", true);
    public static final b<Boolean> aNe = d("mute_controls_enabled", false);
    public static final b<Boolean> aNf = d("allow_user_muting", true);
    public static final b<Boolean> aNg = d("mute_videos", false);
    public static final b<Boolean> aNh = d("show_mute_by_default", false);
    public static final b<Boolean> aNi = d("mute_with_user_settings", true);
    public static final b<Integer> aNj = d("mute_button_size", 32);
    public static final b<Integer> aNk = d("mute_button_margin", 10);
    public static final b<Integer> aNl = d("mute_button_gravity", 85);
    public static final b<Long> aNm = d("progress_bar_step", 25L);
    public static final b<Integer> aNn = d("progress_bar_scale", 10000);
    public static final b<Integer> aNo = d("progress_bar_vertical_padding", -8);
    public static final b<Integer> aNp = d("vs_buffer_indicator_size", 50);
    public static final b<Boolean> aNq = d("video_zero_length_as_computed", false);
    public static final b<Long> aNr = d("set_poststitial_muted_initial_delay_ms", 500L);
    public static final b<Boolean> aNs = d("fasuic", true);
    public static final b<Boolean> aNt = d("fsahrpg", true);
    public static final b<Boolean> aNu = d("eaafrwsoa", true);
    public static final b<Long> aNv = d("postitial_progress_bar_step_ms", 25L);
    public static final b<Boolean> aNw = d("postitial_progress_bar_on_bottom", true);
    public static final b<Integer> aNx = d("postitial_progress_bar_vertical_padding", -8);
    public static final b<Integer> aNy = d("postitial_progress_bar_scale", 10000);
    public static final b<Boolean> aNz = d("sutfaa", true);
    public static final b<Boolean> aOA = d("qq10", true);
    public static final b<Boolean> aOB = d("qq11", true);
    public static final b<Boolean> aOC = d("pui", true);
    public static final b<String> aOD = d("plugin_version", "");
    public static final b<Boolean> aOE = d("hgn", true);
    public static final b<Boolean> aOF = d("cso", true);
    public static final b<Boolean> aOG = d("cfs", true);
    public static final b<Boolean> aOH = d("cmi", true);
    public static final b<Boolean> aOI = d("crat", true);
    public static final b<Boolean> aOJ = d("cvs", true);
    public static final b<Boolean> aOK = d("caf", true);
    public static final b<Boolean> aOL = d("cf", true);
    public static final b<Boolean> aOM = d("cmtl", true);
    public static final b<Boolean> aON = d("cnr", true);
    public static final b<Boolean> aOO = d("ccr", false);
    public static final b<Boolean> aOP = d("adr", true);
    public static final b<Float> aOQ = d("volume_normalization_factor", Float.valueOf(6.6666665f));
    public static final b<Boolean> aOR = d("system_user_agent_collection_enabled", false);
    public static final b<Boolean> aOS = d(AppLovinSdkExtraParameterKey.USER_AGENT_COLLECTION_ENABLED, false);
    public static final b<Boolean> aOT = d("collect_device_angle", true);
    public static final b<Boolean> aOU = d("collect_device_movement", true);
    public static final b<Boolean> aOV = d("cipc", true);
    public static final b<Float> aOW = d("movement_degradation", Float.valueOf(0.75f));
    public static final b<Integer> aOX = d("device_sensor_period_ms", Integer.valueOf(IronSourceConstants.INTERSTITIAL_DAILY_CAPPED));
    public static final b<Boolean> aOY = d("idcw", false);
    public static final b<Integer> aOZ = d("fetch_basic_settings_delay_ms", 1500);
    public static final b<Boolean> aOa = d("falawpr", false);
    public static final b<Boolean> aOb = d("sort_query_parameters", false);
    public static final b<Long> aOc = d("communicator_request_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10)));
    public static final b<Integer> aOd = d("communicator_request_retry_count", 3);
    public static final b<Long> aOe = d("communicator_request_retry_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(2)));
    public static final b<Long> aOf = d("rfbsd_ms", -1L);
    public static final b<Long> aOg = d("ehkpd_ms", 500L);
    public static final b<Boolean> aOh = d("rironc", false);
    public static final b<Boolean> aOi = d("rroncbd", false);
    public static final b<Long> aOj = d("wverc_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5)));
    public static final b<Integer> aOk = d("ad_session_minutes", 60);
    public static final b<Boolean> aOl = d("session_tracking_cooldown_on_event_fire", true);
    public static final b<Long> aOm = d("session_tracking_resumed_cooldown_minutes", 90L);
    public static final b<Long> aOn = d("session_tracking_paused_cooldown_minutes", 90L);
    public static final b<Boolean> aOo = d("dc_v2", false);
    public static final b<Boolean> aOp = d("dce", true);
    public static final b<Boolean> aOq = d("qq", false);
    public static final b<Boolean> aOr = d("qq1", true);
    public static final b<Boolean> aOs = d("qq2", true);
    public static final b<Boolean> aOt = d("qq3", true);
    public static final b<Boolean> aOu = d("qq4", true);
    public static final b<Boolean> aOv = d("qq5", true);
    public static final b<Boolean> aOw = d("qq6", true);
    public static final b<Boolean> aOx = d("qq7", true);
    public static final b<Boolean> aOy = d("qq8", true);
    public static final b<Boolean> aOz = d("qq9", false);
    public static final b<Integer> aPA = d("vast_industry_icon_margin", 12);
    public static final b<Integer> aPB = d("vast_industry_icon_gravity", 85);
    public static final b<Integer> aPC = d("vast_native_mute_button_size", 24);
    public static final b<Integer> aPD = d("vast_native_play_pause_button_size", 24);
    public static final b<Integer> aPE = d("vast_native_video_widget_padding", 6);
    public static final b<Float> aPF = d("vast_native_video_widget_alpha", Float.valueOf(0.5f));
    public static final b<Boolean> aPG = d("vast_native_video_widgets_enabled", true);
    public static final b<Boolean> aPH = d("vast_replay_video_upon_completion", true);
    public static final b<Integer> aPI = d("vast_replay_icon_size", 64);
    public static final b<Boolean> aPJ = d("vcjfhr", false);
    public static final b<String> aPK = d("vcjfhrr", "(?:<|%3C)script[^>]*src=\"(https[^\"]*\\.js[^\"]*)\".*?(?:>|%3E)");
    public static final b<Boolean> aPL = d("ree", true);
    public static final b<Integer> aPM = d("ree_t", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Boolean> aPN = d("btee", true);
    public static final b<Integer> aPO = d("btet", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Boolean> aPP = d("reetoa", false);
    public static final b<Integer> aPQ = d("reet_msfs", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPR = d("reet_msma", Integer.valueOf(p.a.V2.getValue()));
    public static final b<Integer> aPS = d("reet_msmd", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPT = d("reet_asfp", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPU = d("reet_asfg", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPV = d("reet_aset", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPW = d("reet_esdi", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Integer> aPX = d("reet_esrp", Integer.valueOf(p.a.DEFAULT.getValue()));
    public static final b<Boolean> aPY = d("apdra", false);
    public static final b<Boolean> aPZ = d("apdrfs", false);
    public static final b<String> aPa = d("mps", "");
    public static final b<Integer> aPb = d("mpsl", 3);
    public static final b<String> aPc = d("mpis", "com.applovin,dalvik,java,android,com.android");
    public static final b<Boolean> aPd = d("cmps", false);
    public static final b<Integer> aPe = d("dcttl_1_seconds", 5);
    public static final b<Integer> aPf = d("dcttl_2_seconds", 30);
    public static final b<Integer> aPg = d("dcttl_3_seconds", Integer.valueOf((int) TimeUnit.MINUTES.toSeconds(1)));
    public static final b<Integer> aPh = d("dcttl_4_seconds", Integer.valueOf((int) TimeUnit.MINUTES.toSeconds(30)));
    public static final b<Integer> aPi = d("dcttl_5_seconds", Integer.valueOf((int) TimeUnit.HOURS.toSeconds(1)));
    public static final b<Integer> aPj = d("dcttl_6_seconds", Integer.valueOf((int) TimeUnit.DAYS.toSeconds(1)));
    public static final b<Boolean> aPk = d("cclia", true);
    public static final b<Long> aPl = d("lccdm", 10L);
    public static final b<Integer> aPm = d("lmfd", 2);
    public static final b<Boolean> aPn = d("is_track_ad_info", true);
    public static final b<Integer> aPo = d("submit_ad_stats_max_count", 500);
    public static final b<String> aPp = d("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
    public static final b<String> aPq = d("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
    public static final b<Integer> aPr = d("vast_max_response_length", 640000);
    public static final b<Integer> aPs = d("vast_max_wrapper_depth", 5);
    public static final b<String> aPt = d("vast_unsupported_video_extensions", "ogv,flv");
    public static final b<String> aPu = d("vast_unsupported_video_types", "video/ogg,video/x-flv");
    public static final b<Boolean> aPv = d("vast_validate_with_extension_if_no_video_type", true);
    public static final b<Integer> aPw = d("vast_video_selection_policy", Integer.valueOf(n.a.MEDIUM.ordinal()));
    public static final b<Integer> aPx = d("vast_wrapper_resolution_retry_count_v1", 1);
    public static final b<Integer> aPy = d("vast_wrapper_resolution_connection_timeout", Integer.valueOf((int) TimeUnit.SECONDS.toMillis(30)));
    public static final b<Integer> aPz = d("vast_industry_icon_max_size", 20);
    public static final b<Boolean> aQA = d("bvde", false);
    public static final b<Long> aQB = d("bvdidm", 1000L);
    public static final b<Long> aQC = d("bvdim", 4000L);
    public static final b<Integer> aQD = d("bvdrs", 10);
    public static final b<Integer> aQE = d("bvdct", 230);
    public static final b<Boolean> aQF = d("bvad", false);
    public static final b<Boolean> aQG = d("bvebb", true);
    public static final b<Boolean> aQH = d("bvscb", true);
    public static final b<Boolean> aQI = d("apsobt", true);
    public static final b<Integer> aQJ = d("tmtp", 1);
    public static final b<Integer> aQK = d("ntp", 5);
    public static final b<Boolean> aQL = d("uwtm", false);
    public static final b<Boolean> aQM = d("dwvvb", false);
    public static final b<Boolean> aQN = d("stcpc", true);
    public static final b<Boolean> aQO = d("stcic", true);
    public static final b<Boolean> aQP = d("ueeem", false);
    public static final b<Boolean> aQQ = d("upspfopsu", false);
    public static final b<Boolean> aQR = d("clacaf", false);
    public static final b<Boolean> aQS = d("qjscwwvl", false);
    public static final b<String> aQT = d("config_consent_dialog_state", "unknown");
    public static final b<String> aQU = d("country_code", "");
    public static final b<String> aQV = d("consent_flow_doc_url", "https://dash.applovin.com/documentation/mediation/android/getting-started/integration#enabling-max-built-in-consent-flow");
    public static final b<String> aQW = d("consent_flow_unity_doc_url", "https://dash.applovin.com/documentation/mediation/unity/getting-started/integration#max-built-in-consent-flow");
    public static final b<Integer> aQX = d("cfadtml", 20);
    public static final b<Boolean> aQY = d("ps_etr", false);
    public static final b<Long> aQZ = d("ps_tri_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7)));
    public static final b<Boolean> aQa = d("apdrma", false);
    public static final b<Boolean> aQb = d("apdrmd", false);
    public static final b<Boolean> aQc = d("apdrfa", false);
    public static final b<Boolean> aQd = d("apdrev", false);
    public static final b<Boolean> aQe = d("apdrdi", false);
    public static final b<Boolean> aQf = d("apdrrp", false);
    public static final b<Long> aQg = d("server_timestamp_ms", 0L);
    public static final b<Long> aQh = d("device_timestamp_ms", 0L);
    public static final b<Integer> aQi = d("gzip_min_length", 0);
    public static final b<Boolean> aQj = d("gzip_encoding_default", false);
    public static final b<Boolean> aQk = d("fetch_settings_gzip", false);
    public static final b<Boolean> aQl = d("device_init_gzip", false);
    public static final b<Boolean> aQm = d("fetch_ad_gzip", false);
    public static final b<Boolean> aQn = d("event_tracking_gzip", false);
    public static final b<Boolean> aQo = d("reward_postback_gzip", false);
    public static final b<Boolean> aQp = d("handle_render_process_gone", true);
    public static final b<Boolean> aQq = d("rworpg", true);
    public static final b<Boolean> aQr = d("fdadaomr", true);
    public static final b<Boolean> aQs = d("teorpc", false);
    public static final b<Boolean> aQt = d("set_webview_render_process_client", false);
    public static final b<Boolean> aQu = d("disable_webview_hardware_acceleration", false);
    public static final b<Boolean> aQv = d("anr_detection_enabled", false);
    public static final b<Long> aQw = d("anr_trigger_millis", 4000L);
    public static final b<Long> aQx = d("anr_touch_millis", 3000L);
    public static final b<Long> aQy = d("anr_check_millis", 3000L);
    public static final b<Boolean> aQz = d("uobid", true);
    public static final b<Long> aRa = d("ps_ftri_ms", -1L);
    public static final b<Boolean> aRb = d("ps_sroftr", false);
    public static final b<Boolean> aRc = d("ps_sroftrof", false);
    public static final b<Boolean> aRd = d("communicator_enabled", true);
    public static final b<Boolean> aRe = d("adse", true);
    private final T aKj;
    private final String name;

    public T JD() {
        return this.aKj;
    }

    public String getName() {
        return this.name;
    }

    public b(String str, T t) {
        if (str == null) {
            throw new IllegalArgumentException("No name specified");
        } else if (t != null) {
            this.name = str;
            this.aKj = t;
        } else {
            throw new IllegalArgumentException("No default value specified");
        }
    }

    public T af(Object obj) {
        return this.aKj.getClass().cast(obj);
    }

    public int compareTo(Object obj) {
        if (!(obj instanceof b)) {
            return 0;
        }
        return this.name.compareTo(((b) obj).getName());
    }

    protected static <T> b<T> d(String str, T t) {
        if (t == null) {
            throw new IllegalArgumentException("No default value specified");
        } else if (aKh.contains(t.getClass())) {
            b<T> bVar = new b<>(str, t);
            Map<String, b<?>> map = aKi;
            if (!map.containsKey(str)) {
                map.put(str, bVar);
                return bVar;
            }
            throw new IllegalArgumentException("Setting has already been used: " + str);
        } else {
            throw new IllegalArgumentException("Unsupported value type: " + t.getClass());
        }
    }

    public static Collection<b<?>> JE() {
        return Collections.synchronizedCollection(aKi.values());
    }
}
