package com.ironsource;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;

public class jc {
    public static final String A = "dLang";
    public static final String A0 = "diskFreeSize";
    public static final String B = "MD";
    public static final String B0 = "appOrientation";
    public static final String C = "uGen";
    public static final String C0 = "asid";
    public static final String D = "advType";
    public static final String D0 = "deviceWidth";
    public static final String E = "isLAT";
    public static final String E0 = "deviceHeight";
    public static final String F = "auid";
    public static final String F0 = "displaySizeWidth";
    public static final String G = "UA";
    public static final String G0 = "displaySizeHeight";
    public static final String H = "omidV";
    public static final String H0 = "deviceScreenScale";
    public static final String I = "omidPV";
    public static final String I0 = "AID";
    public static final String J = "imm";
    public static final String J0 = "isLimitAdTrackingEnabled";
    public static final String K = "appOr";
    public static final String K0 = "unLocked";
    public static final String L = "sdkV";
    public static final String L0 = "deviceVolume";
    public static final String M = "dScrenScle";
    public static final String M0 = "immersiveMode";
    public static final String N = "pType";
    public static final String N0 = "simOperator";
    public static final String O = "simOp";
    public static final String O0 = "phoneType";
    public static final String P = "lUpdateT";
    public static final String P0 = "mcc";
    public static final String Q = "fInstallT";
    public static final String Q0 = "mnc";
    public static final String R = "dSizeW";
    public static final String R0 = "lastUpdateTime";
    public static final String S = "dSizeH";
    public static final String S0 = "appVersion";
    public static final String T = "cellNetT";
    public static final String T0 = "firstInstallTime";
    public static final String U = "vpn";
    public static final String U0 = "batteryLevel";
    public static final String V = "dVol";
    public static final String V0 = "consent";
    public static final String W = "sdCrdAvail";
    public static final String W0 = "installerPackageName";
    public static final String X = "isCharge";
    public static final String X0 = "localTime";
    public static final String Y = "chargeT";
    public static final String Y0 = "clientTimestamp";
    public static final String Z = "airM";
    public static final String Z0 = "timezoneOffset";
    public static final String a = "uAge";
    public static final String a0 = "onWhnPlugIn";
    public static final String a1 = "sdCardAvailable";
    public static final String b = "advId";
    public static final String b0 = "dRAM";
    public static final String b1 = "totalDeviceRAM";
    public static final String c = "appKey";
    public static final String c0 = "iPckgN";
    public static final String c1 = "isCharging";
    public static final String d = "mCar";
    public static final String d0 = "tzOff";
    public static final String d1 = "chargingType";
    public static final String e = "medV";
    public static final String e0 = "cnaCDN";
    public static final String e1 = "airplaneMode";
    public static final String f = "connT";
    public static final String f0 = "applicationUserId";
    public static final String f1 = "stayOnWhenPluggedIn";
    public static final String g = "dWidth";
    public static final String g0 = "applicationKey";
    public static final String g1 = "SDKPluginType";
    public static final String h = "dHeight";
    public static final String h0 = "sessionDepthRV";
    public static final String h1 = "advertisingId";
    public static final String i = "dModel";
    public static final String i0 = "sessionDepthIS";
    public static final String i1 = "advIdType";
    public static final String j = "cTime";
    public static final String j0 = "sessionId";
    public static final String j1 = "applicationUserGender";
    public static final String k = "sDepRV";
    public static final String k0 = "deviceOEM";
    public static final String k1 = "applicationUserAge";
    public static final String l = "sDepIS";
    public static final String l0 = "deviceModel";
    public static final String l1 = "metadata";
    public static final String m = "sId";
    public static final String m0 = "deviceMake";
    public static final String m1 = "bundleId";
    public static final String n = "plType";
    public static final String n0 = "deviceIds[AID]";
    public static final String n1 = "omidVersion";
    public static final String o = "dOSV";
    public static final String o0 = "deviceOs";
    public static final String o1 = "omidPartnerVersion";
    public static final String p = "dOSVF";
    public static final String p0 = "deviceOS";
    public static final String p1 = "chinaCDN";
    public static final String q = "dOS";
    public static final String q0 = "deviceOSVersion";
    public static final String q1 = "applicationUserAgeGroup";
    public static final String r = "dMake";
    public static final String r0 = "deviceOSVersionFull";
    public static final String r1 = "metadata_";
    public static final String s = "dAPI";
    public static final String s0 = "deviceApiLevel";
    private static final String s1 = "Gpi";
    public static final String t = "bId";
    public static final String t0 = "SDKVersion";
    private static final String t1 = "blacklistedCampaigns";
    public static final String u = "appV";
    public static final String u0 = "MedSDKVersion";
    private static final String u1 = "biddingRVImpressions";
    public static final String v = "usId";
    public static final String v0 = "mobileCarrier";
    private static final String v1 = "biddingISImpressions";
    public static final String w = "bat";
    public static final String w0 = "connectionType";
    private static final String w1 = "totalRVSessionImpressions";
    public static final String x = "lpm";
    public static final String x0 = "cellularNetworkType";
    private static final String x1 = "totalISSessionImpressions";
    public static final String y = "root";
    public static final String y0 = "hasVPN";
    public static final ArrayList<String> y1 = new ArrayList<>(Arrays.asList(new String[]{q1, a, b, "appKey", d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, "bat", y, z, A, B, C, D, E, V, "consent", h, g, M, "auid", G, "asid"}));
    public static final String z = "diskFS";
    public static final String z0 = "deviceLanguage";
    public static final HashMap<String, String> z1 = new a();

    class a extends HashMap<String, String> {
        a() {
            put("omidVersion", jc.H);
            put("omidPartnerVersion", jc.I);
            put("immersiveMode", "imm");
            put("appOrientation", jc.K);
            put("SDKVersion", jc.L);
            put("deviceScreenScale", jc.M);
            put("phoneType", jc.N);
            put("simOperator", jc.O);
            put("lastUpdateTime", jc.P);
            put("firstInstallTime", jc.Q);
            put("displaySizeWidth", jc.g);
            put("displaySizeHeight", jc.h);
            put(jc.x0, jc.T);
            put("hasVPN", "vpn");
            put("deviceVolume", jc.V);
            put("sdCardAvailable", jc.W);
            put("isCharging", jc.X);
            put("chargingType", jc.Y);
            put("airplaneMode", jc.Z);
            put("stayOnWhenPluggedIn", jc.a0);
            put("totalDeviceRAM", jc.b0);
            put("installerPackageName", jc.c0);
            put("timezoneOffset", jc.d0);
            put("chinaCDN", jc.e0);
            put("deviceOs", jc.q);
            put("localTime", jc.j);
            put(jc.n0, jc.b);
            put(jc.k1, jc.a);
            put(jc.h1, jc.b);
            put(jc.i1, jc.D);
            put(jc.D0, jc.g);
            put(jc.E0, jc.h);
            put(jc.p0, jc.q);
            put(jc.Y0, jc.j);
            put(jc.h0, jc.k);
            put(jc.i0, jc.l);
            put("sessionId", jc.m);
            put(jc.u0, jc.e);
            put(jc.m0, jc.r);
            put(jc.j1, jc.C);
            put("batteryLevel", "bat");
            put("unLocked", jc.y);
            put("deviceOSVersion", jc.o);
            put("bundleId", jc.t);
            put("mobileCarrier", jc.d);
            put("connectionType", jc.f);
            put("appVersion", jc.u);
            put("applicationKey", "appKey");
            put("applicationUserId", jc.v);
            put("isLimitAdTrackingEnabled", jc.E);
            put(jc.l1, jc.B);
            put("deviceModel", jc.i);
            put(jc.g1, jc.n);
            put("deviceApiLevel", jc.s);
            put("diskFreeSize", jc.z);
            put("deviceLanguage", jc.A);
            put("deviceOEM", jc.r);
            put("deviceOSVersionFull", jc.p);
        }
    }
}
