package com.ironsource;

public class z3 {
    public static final String A = "timingvalue";
    public static final String B = "inAppBidding";
    public static final String C = "rewarded";
    public static final Object D = "initialized instance";
    public static final Object E = "uninitialized instance";
    public static final String F = "isoneflow";
    public static final String G = "custom_c";
    public static final String H = "custom_b";
    public static final String I = "Content-Type";
    public static final String J = "application/json";
    public static final String K = "charset";
    public static final String L = "utf-8";
    public static final String M = "events";
    public static final boolean N = true;
    public static final String O = "table";
    public static final String P = "supersonic.adunitanalytics.ad_unit_events";
    public static final String Q = "data";
    public static final char R = '=';
    public static final String S = "logEvent failed eventsTracker doesn't exist";
    public static final String a = "sdk5Events";
    public static final String b = "sdkversion";
    public static final String c = "n_";
    public static final String d = "bundleid";
    public static final String e = "connectiontype";
    public static final String f = "applicationkey";
    public static final String g = "sessionid";
    public static final String h = "applicationuserid";
    public static final String i = "deviceos";
    public static final String j = "deviceosversion";
    public static final String k = "deviceapilevel";
    public static final String l = "deviceoem";
    public static final String m = "devicemodel";
    public static final String n = "env";
    public static final String o = "origin";
    public static final String p = "n";
    public static final String q = "endpoint";
    public static final String r = "enabled";
    public static final String s = "prod";
    public static final String t = "eventid";
    public static final String u = "demandsourcename";
    public static final String v = "producttype";
    public static final String w = "isbiddinginstance";
    public static final String x = "generalmessage";
    public static final String y = "controllersource";
    public static final String z = "callfailreason";
}
